config/routes.rb
Jetsi::Application.routes.draw do
  resources :currencies do
    collection { post :import }
  end

  root  'static_pages#home'
  match '/privacy',     to: 'static_pages#privacy',   via: 'get'
  match '/terms',       to: 'static_pages#terms',     via: 'get'
  match '/business',    to: 'currencies#business',    via: 'get'
  match '/tourism',    to: 'currencies#index',        via: 'get'
  match '/timeline',    to: 'static_pages#timeline',  via: 'get'
  match '/businesstimeline',    to: 'static_pages#businesstimeline',  via: 'get'
  match '/events',      to: 'static_pages#events',    via: 'get'

end

app/models/currency.rb
require 'csv'

class Currency < ActiveRecord::Base
  translates :name
	
	def self.import(file)
    	CSV.foreach(file.path, headers: true) do |row|
      		currency = Currency.find_by(keyid: row[0])
      		if currency.nil?
        		Currency.create!(
          		:keyid => row[0],
              :name => row[1],
              :currencyname => row[2],
          		:region => row[3],
              :livingcost => row[4],
              :bmi => row[5],
          		:weeklychange => row[6],
          		:monthlychange => row[7],
          		:yearlychange => row[8],
          		:currencyfor => row[9],
              :wikilink => row[10],
              :commute => row[11],
              :utilities => row[12],
              :internet => row[13],
              :apt => row[14],
              :salary => row[15],
              :dinner => row[16],
              :cities => row[17]
        		)
      		else
        		currency.update_attributes(
          		:monthlychange => row[7],
          		:yearlychange => row[8],
              :commute => row[11],
              :utilities => row[12],
              :internet => row[13],
              :apt => row[14],
              :salary => row[15],
              :dinner => row[16],
              :cities => row[17]
        		)
     		end
     	end

    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_locale
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def default_url_options(options={})
  	{ locale: I18n.locale }
  end

  private
  	def set_locale
      I18n.locale = params[:locale] || I18n.default_locale
    end
end

app/controllers/currencies_controller.rb
class CurrenciesController < ApplicationController
  before_action :set_currency, only: [:show, :edit, :update, :destroy]

  helper_method :sort_column, :sort_direction

  # GET /currencies
  # GET /currencies.json
  def index
    @USDcurrencies = Currency.where(:currencyfor => 'USD')
    @EURcurrencies = Currency.where(:currencyfor => 'EUR')
    @GBPcurrencies = Currency.where(:currencyfor => 'GBP')
    @JPYcurrencies = Currency.where(:currencyfor => 'JPY')
    @CNYcurrencies = Currency.where(:currencyfor => 'CNY')
  end

  def business
    @USDcurrencies = Currency.where(:currencyfor => 'USD')
    @EURcurrencies = Currency.where(:currencyfor => 'EUR')
    @GBPcurrencies = Currency.where(:currencyfor => 'GBP')
    @JPYcurrencies = Currency.where(:currencyfor => 'JPY')
    @CNYcurrencies = Currency.where(:currencyfor => 'CNY')
  end

  # GET /currencies/1
  # GET /currencies/1.json
  def show
  end

  # GET /currencies/new
  def new
    @currency = Currency.new
  end

  # GET /currencies/1/edit
  def edit
  end

  # POST /currencies
  # POST /currencies.json
  def create
    @currency = Currency.new(currency_params)

    respond_to do |format|
      if @currency.save
        format.html { redirect_to @currency, notice: 'Currency was successfully created.' }
        format.json { render action: 'show', status: :created, location: @currency }
      else
        format.html { render action: 'new' }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /currencies/1
  # PATCH/PUT /currencies/1.json
  def update
    respond_to do |format|
      if @currency.update(currency_params)
        format.html { redirect_to @currency, notice: 'Currency was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @currency.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /currencies/1
  # DELETE /currencies/1.json
  def destroy
    @currency.destroy
    respond_to do |format|
      format.html { redirect_to currencies_url }
      format.json { head :no_content }
    end
  end

  #import csv file
  def import
   Currency.import(params[:file])
   redirect_to :back, notice: "Exchange rates imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_currency
      @currency = Currency.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def currency_params
      params.require(:currency).permit(:name, :region, :weeklychange, :monthlychange, :yearlychange, :currencyfor, :livingcost, 
        :bmi, :currencyname, :keyid, :wikilink, :commute, :utilities, :internet, :apt, :salary, :dinner, :cities)
    end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	@header2 = true
  	@skip_footer = true
  end
  def terms
  end

  def privacy
  end

  def timeline
  end

  def businesstimeline
  end

  def events
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

	# Returns the full title on a per-page basis.
	def full_title(page_title)
		base_title = "Jetsi"
		if page_title.empty?
		  base_title
		else
		  "#{base_title} | #{page_title}"
		end
	end

end

app/helpers/currencies_helper.rb
module CurrenciesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/currencies/_bizcurrencies.html.erb
<table cellpadding="0" cellspacing="0" border="0" class="table table-bordered display order-column table-hover">
  <thead>
    <tr class="business">
      <th data-class="expand"><%= t 'jumbotron.table.symbol' %></th>
      <th data-hide="phone,tablet"><%= t 'jumbotron.table.country' %></th>
      <th data-hide="phone,tablet,lg"><%= t 'jumbotron.table.costofliving' %></th>
      <th data-hide="phone,tablet,lg"><%= t 'jumbotron.table.bigmac' %></th>
      <th data-hide="phone" class="util">Utilities/85m² (electric, heat, water, garbage)</th>
      <th data-hide="phone,tablet">Internet (6mbps)</th>
      <th data-hide="phone, tablet">Monthly Transit</th>
      <th data-hide="phone,tablet,lg">3bdr Apartment Downtown</th>
      <th>Avg. Monthly Salary</th>
      <th data-hide="phone,tablet,lg"><i class="fa fa-exchange"></i> <%= t 'jumbotron.table.month' %></th>
      <th><i class="fa fa-exchange year"></i> <%= t 'jumbotron.table.year' %></th>
    </tr>
  </thead>

  <tbody>
    <% currencies.each do |currency| %>
      <tr>
          <td><%= currency.currencyname %><a href="<%= currency.wikilink %>" target="_blank"><i class="fa fa-info-circle linkicon"></i></a></td>
          <td><%= currency.name %></td>
          <td><a href="<%= currency.livingcost %>" target="_blank"><i class="fa fa-external-link fa-lg"></i></a></td>
          <td><%= number_to_currency(currency.bmi, unit: symbol) %></td>
          <td><%= number_to_currency(currency.commute, unit: symbol) %></td>
          <td><%= number_to_currency(currency.utilities, unit: symbol) %></td>
          <td><%= number_to_currency(currency.internet, unit: symbol) %></td>
          <td><%= number_to_currency(currency.apt, unit: symbol) %></td>
          <td><%= number_to_currency(currency.salary, unit: symbol) %></td>
          <td>
            <% unless currency.monthlychange < 0 %>
              +
            <% end %>
            <%= number_to_percentage(currency.monthlychange * 100, precision: 2) %>
            <% if currency.monthlychange > 0 %>
              <span class="glyphicon glyphicon-arrow-up iconright iconup"></span>
            <% elsif currency.monthlychange < 0 %>
              <span class="glyphicon glyphicon-arrow-down iconright icondown"></span>
            <% end %>
          </td>
          <td>
            <% unless currency.yearlychange < 0 %>
              +
            <% end %>
            <%= number_to_percentage(currency.yearlychange * 100, precision: 2) %> 
            <% if currency.yearlychange > 0 %>
              <span class="glyphicon glyphicon-arrow-up iconright iconup"></span>
            <% elsif currency.yearlychange < 0 %>
              <span class="glyphicon glyphicon-arrow-down iconright icondown"></span>
            <% end %>
          </td>
          <!-- <td><%= link_to 'Show', currency %></td>
          <td><%= link_to 'Edit', edit_currency_path(currency) %></td>
          <td><%= link_to 'Destroy', currency, method: :delete, data: { confirm: 'Are you sure?' } %></td> -->
      </tr>
    <% end %>
  </tbody>
</table>

app/views/currencies/business.html.erb
<div class="center jumbotron" id="maindisplay">
  <h1>
    Let your capital work for you while touring the world
  </h1>

  <h3>(<%= t 'jumbotron.directions' %>)</h3>
  

  <div id="tabs" class="tabs">
    <nav>
      <ul>
        <li><a href="#section-1" class="icon-shop" type="submit" name="index" value="USD"><span>USD</span></a></li>
        <li><a href="#section-2" class="icon-cup" type="submit" name="index" value="EUR"><span>EUR</span></a></li>
        <li><a href="#section-3" class="icon-food" type="submit" name="index" value="GBP"><span>GBP</span></a></li>
        <li><a href="#section-4" class="icon-lab" type="submit" name="index" value="JPY"><span>JPY</span></a></li>
        <li><a href="#section-5" class="icon-truck" type="submit" name="index" value="CNY"><span>CNY</span></a></li>
      </ul>
    </nav>
    <div class="content">
      <section id="section-1">
        <span class="ratechanges">
          *<%= t 'jumbotron.section1' %> <i class="fa fa-exchange"></i><br>
          (<span class="glyphicon glyphicon-arrow-up iconup"></span><%= t 'jumbotron.favorable' %>, <span class="glyphicon glyphicon-arrow-down icondown"></span><%= t 'jumbotron.unfavorable' %>)
        </span>
        <div id="currencies"><%= render 'bizcurrencies', :currencies => @USDcurrencies, :symbol => "$ " %></div>
      </section>
      <section id="section-2">
        <span class="ratechanges">
          *<%= t 'jumbotron.section1' %> <i class="fa fa-exchange"></i><br>
          (<span class="glyphicon glyphicon-arrow-up iconup"></span><%= t 'jumbotron.favorable' %>, <span class="glyphicon glyphicon-arrow-down icondown"></span><%= t 'jumbotron.unfavorable' %>)
        </span>
        <div id="currencies"><%= render 'bizcurrencies', :currencies => @EURcurrencies, :symbol => "€ " %></div>
      </section>
      <section id="section-3">
        <span class="ratechanges">
          *<%= t 'jumbotron.section1' %> <i class="fa fa-exchange"></i><br>
          (<span class="glyphicon glyphicon-arrow-up iconup"></span><%= t 'jumbotron.favorable' %>, <span class="glyphicon glyphicon-arrow-down icondown"></span><%= t 'jumbotron.unfavorable' %>)
        </span>
        <div id="currencies"><%= render 'bizcurrencies', :currencies => @GBPcurrencies, :symbol => "£ " %></div>
      </section>
      <section id="section-4">
        <span class="ratechanges">
          *<%= t 'jumbotron.section1' %> <i class="fa fa-exchange"></i><br>
          (<span class="glyphicon glyphicon-arrow-up iconup"></span><%= t 'jumbotron.favorable' %>, <span class="glyphicon glyphicon-arrow-down icondown"></span><%= t 'jumbotron.unfavorable' %>)
        </span>
        <div id="currencies"><%= render 'bizcurrencies', :currencies => @JPYcurrencies, :symbol => "¥ " %></div>
      </section>
      <section id="section-5">
        <span class="ratechanges">
          *<%= t 'jumbotron.section1' %> <i class="fa fa-exchange"></i><br>
          (<span class="glyphicon glyphicon-arrow-up iconup"></span><%= t 'jumbotron.favorable' %>, <span class="glyphicon glyphicon-arrow-down icondown"></span><%= t 'jumbotron.unfavorable' %>)
        </span>
        <div id="currencies"><%= render 'bizcurrencies', :currencies => @CNYcurrencies, :symbol => "¥ " %></div>
      </section>
      <div id="buyingpower">
        <button type="button" class="btn btn-info" data-container="body" data-toggle="popover" data-placement="bottom" data-content="<%= t 'jumbotron.table.info' %>">
          <%= t 'jumbotron.table.directions' %>&nbsp;
          <i class="fa fa-question-circle fa-lg"></i>
        </button>&nbsp;&nbsp;<script>$(function () { $("[data-toggle='popover']").popover(); });</script>
        <button type="button" class="btn btn-info">
          <%= link_to 'How do I benefit  <i class="fa fa-question-circle fa-lg"></i>'.html_safe, timeline_path %>
        </button>&nbsp;&nbsp;
        <button type="button" class="btn btn-info">
          <%= link_to 'Where should I go  <i class="fa fa-question-circle fa-lg"></i>'.html_safe, events_path %>
        </button>&nbsp;&nbsp;
      </div>
    </div><!-- /content -->
  </div><!-- /tabs -->
  <script>
      new CBPFWTabs( document.getElementById( 'tabs' ) );
  </script>
  <script>
    $( document ).ready(function() {
      var $newdiv1 = $( "<div class='input-group'>"),
        $newspan1 = $( "<span class='input-group-addon glyphicon glyphicon-search'/>");
      $('div.dataTables_filter label').prepend( $newspan1 ).addClass("input-group");
      $('div.dataTables_filter input').addClass("form-control").attr("placeholder", "<%= t 'jumbotron.table.search' %>");
    });
  </script>

  <br>
</div>

<div class="connect">
  <span><%= t 'connect.title' %></span><br>
  <a href="https://www.facebook.com/ForeignSavvy" target="_blank"><i class="fa fa-facebook-square fa-2x"></i></a>&nbsp;
  <a href="https://twitter.com/ForeignSavvy" target="_blank"><i class="fa fa-twitter-square fa-2x"></i></a>&nbsp;
  <a href="http://eepurl.com/WltST" class="btn btn-large btn-primary subscribe"><%= t 'connect.subscribe' %> <i class="fa fa-envelope"></i></a>
</div>


<div class="panel-group" id="accordion">
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
          <i class="fa fa-check-square-o fa-lg"></i>&nbsp;<%= t 'panels.title1' %><i class="fa fa-plus-square iconright"></i>
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse in">
      <div class="panel-body">
        <ul><%= t 'panels.body1_html' %></ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseTwo">
          <i class="fa fa-check-square-o fa-lg"></i>&nbsp;<%= t 'panels.title2' %><i class="fa fa-plus-square iconright"></i>
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse">
      <div class="panel-body">
        <ul><%= t 'panels.body2_html' %></ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="#collapseThree">
          <i class="fa fa-check-square-o fa-lg"></i>&nbsp;<%= t 'panels.title3' %><i class="fa fa-plus-square iconright"></i>
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse">
      <div class="panel-body">
        <ul><%= t 'panels.body3_html', :bpi => link_to("The Backpacker Index", "http://www.priceoftravel.com/2222/world-cities-by-price-backpacker-index/"), :bmi => link_to("The Big Mac Index", "http://www.economist.com/content/big-mac-index"), :oan => link_to("Oanda", "http://www.oanda.com/currency/converter/") %></ul>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading">
      <h4 class="panel-title">
        <a data-toggle="collapse" data-parent="#accordion" href="http://www.oanda.com/currency/travel-exchange-rates">
          <i class="fa fa-check-square-o fa-lg"></i>&nbsp;<a href="http://www.oanda.com/currency/travel-exchange-rates" target="_blank"><%= t 'panels.title4' %></a><i class="fa fa-external-link iconright"></i>
        </a>
      </h4>
    </div>
  </div>
</div>
<!--
<div class="ourchoice center">
  <h1><%= t 'ourchoice.title' %><br><span class="glyphicon glyphicon-chevron-down"></span></h1>
</div>
-->
<section>
  <div class="morph-button morph-button-modal morph-button-modal-1 morph-button-fixed">
    <button type="button"><%= t 'about.title' %></button>
    <div class="morph-content">
      <div>
        <div class="content-style-text">
          <h2>Foreign Savvy</h2>
          <p><%= t 'about.text_html' %></p>
          <span class="icon icon-close"></span><br>
          <a href="http://eepurl.com/WltST"><%= t 'connect.subscribe' %></a>
        </div>
      </div>
    </div>
  </div><!-- morph-button -->
</section>

<script>
  (function() { 
    var docElem = window.document.documentElement, didScroll, scrollPosition;

    // trick to prevent scrolling when opening/closing button
    function noScrollFn() {
      window.scrollTo( scrollPosition ? scrollPosition.x : 0, scrollPosition ? scrollPosition.y : 0 );
    }

    function noScroll() {
      window.removeEventListener( 'scroll', scrollHandler );
      window.addEventListener( 'scroll', noScrollFn );
    }

    function scrollFn() {
      window.addEventListener( 'scroll', scrollHandler );
    }

    function canScroll() {
      window.removeEventListener( 'scroll', noScrollFn );
      scrollFn();
    }

    function scrollHandler() {
      if( !didScroll ) {
        didScroll = true;
        setTimeout( function() { scrollPage(); }, 60 );
      }
    };

    function scrollPage() {
      scrollPosition = { x : window.pageXOffset || docElem.scrollLeft, y : window.pageYOffset || docElem.scrollTop };
      didScroll = false;
    };

    scrollFn();

    var UIBtnn = new UIMorphingButton( document.querySelector( '.morph-button' ), {
      closeEl : '.icon-close',
      onBeforeOpen : function() {
        // don't allow to scroll
        noScroll();
      },
      onAfterOpen : function() {
        // can scroll again
        canScroll();
      },
      onBeforeClose : function() {
        // don't allow to scroll
        noScroll();
      },
      onAfterClose : function() {
        // can scroll again
        canScroll();
      }
    } );
  })();
</script>

<div class="main">
  <ul id="cbp-bislideshow" class="cbp-bislideshow">
    <li><%= image_tag("image1__compressed.jpg", alt: "Beach") %></li>
    <li><%= image_tag("image2__compressed.jpg", alt: "Beach Bus") %></li>
    <li><%= image_tag("image3__compressed.jpg", alt: "Eiffel Tower") %></li>
    <li><%= image_tag("image4__compressed.jpg", alt: "Beach Bus") %></li>
    <li><%= image_tag("image5__compressed.jpg", alt: "Locks in Paris") %></li>
    <li><%= image_tag("image6__compressed.jpg", alt: "Mountain") %></li>
  </ul>
</div>
  <script>
    (function(c,q){var m="data:image/gif;base64,R0lGODlhAQABAIAAAAAAAP///ywAAAAAAQABAAACAUwAOw==";c.fn.imagesLoaded=function(f){function n(){var b=c(j),a=c(h);d&&(h.length?d.reject(e,b,a):d.resolve(e));c.isFunction(f)&&f.call(g,e,b,a)}function p(b){k(b.target,"error"===b.type)}function k(b,a){b.src===m||-1!==c.inArray(b,l)||(l.push(b),a?h.push(b):j.push(b),c.data(b,"imagesLoaded",{isBroken:a,src:b.src}),r&&d.notifyWith(c(b),[a,e,c(j),c(h)]),e.length===l.length&&(setTimeout(n),e.unbind(".imagesLoaded",
    p)))}var g=this,d=c.isFunction(c.Deferred)?c.Deferred():0,r=c.isFunction(d.notify),e=g.find("img").add(g.filter("img")),l=[],j=[],h=[];c.isPlainObject(f)&&c.each(f,function(b,a){if("callback"===b)f=a;else if(d)d[b](a)});e.length?e.bind("load.imagesLoaded error.imagesLoaded",p).each(function(b,a){var d=a.src,e=c.data(a,"imagesLoaded");if(e&&e.src===d)k(a,e.isBroken);else if(a.complete&&a.naturalWidth!==q)k(a,0===a.naturalWidth||0===a.naturalHeight);else if(a.readyState||a.complete)a.src=m,a.src=d}):
    n();return d?d.promise(g):g}})(jQuery);
  </script>
  <script>
    var cbpBGSlideshow=(function(){var l=$("#cbp-bislideshow"),g=l.children("li"),n=g.length,f=$("#cbp-bicontrols"),c={$navPrev:f.find("span.cbp-biprev"),$navNext:f.find("span.cbp-binext"),$navPlayPause:f.find("span.cbp-bipause")},h=0,e,k=true,b=3500;function m(o){l.imagesLoaded(function(){if(Modernizr.backgroundsize){g.each(function(){var p=$(this);p.css("background-image","url("+p.find("img").attr("src")+")")})}else{l.find("img").show()}g.eq(h).css("opacity",1);j();a()})}function j(){c.$navPlayPause.on("click",function(){var o=$(this);if(o.hasClass("cbp-biplay")){o.removeClass("cbp-biplay").addClass("cbp-bipause");a()}else{o.removeClass("cbp-bipause").addClass("cbp-biplay");i()}});c.$navPrev.on("click",function(){d("prev");if(k){a()}});c.$navNext.on("click",function(){d("next");if(k){a()}})}function d(q){var p=g.eq(h);if(q==="next"){h=h<n-1?++h:0}else{if(q==="prev"){h=h>0?--h:n-1}}var o=g.eq(h);p.css("opacity",0);o.css("opacity",1)}function a(){k=true;clearTimeout(e);e=setTimeout(function(){d("next");a()},b)}function i(){k=false;clearTimeout(e)}return{init:m}})();
  </script>
  <script>
    $(function() {
      cbpBGSlideshow.init();
    });
  </script>

app/views/currencies/edit.html.erb
<h1>Editing currency</h1>

<%= render 'form' %>

<%= link_to 'Show', @currency %> |
<%= link_to 'Back', currencies_path %>

app/views/currencies/new.html.erb
<p id="notice"><%= notice %></p>
<h1>New currency</h1>

<%= render 'form' %>
<br>
-- import csv --

<%= form_tag import_currencies_path, multipart: true do %>
    <p>1.<br><%= file_field_tag :file %></p>
    <br>
    <p>2.<%= submit_tag "Import" %></p>
<% end %>

<%= link_to 'Back', currencies_path %>

app/views/currencies/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>keyid:</strong>
  <%= @currency.keyid %>
</p>

<p>
  <strong>Name:</strong>
  <%= @currency.name %>
</p>

<p>
  <strong>Currency Name:</strong>
  <%= @currency.currencyname %>
</p>

<p>
  <strong>Region:</strong>
  <%= @currency.region %>
</p>

<p>
  <strong>Cost of Living:</strong>
  <%= @currency.livingcost %>
</p>

<p>
  <strong>BMI:</strong>
  <%= @currency.bmi %>
</p>

<p>
  <strong>Currencyfor:</strong>
  <%= @currency.currencyfor %>
</p>

<p>
  <strong>Weeklychange:</strong>
  <%= @currency.weeklychange %>
</p>

<p>
  <strong>Monthlychange:</strong>
  <%= @currency.monthlychange %>
</p>

<p>
  <strong>Yearlychange:</strong>
  <%= @currency.yearlychange %>
</p>

<p>
  <strong>Wikilink:</strong>
  <%= @currency.wikilink %>
</p>

<p>
  <strong>Commute:</strong>
  <%= @currency.commute %>
</p>

<p>
  <strong>Utilities:</strong>
  <%= @currency.utilities %>
</p>

<p>
  <strong>Internet:</strong>
  <%= @currency.internet %>
</p>

<p>
  <strong>Apt:</strong>
  <%= @currency.apt %>
</p>

<p>
  <strong>Salary:</strong>
  <%= @currency.salary%>
</p>

<p>
  <strong>Dinner for 2:</strong>
  <%= @currency.dinner %>
</p>

<p>
  <strong>Popular Cities:</strong>
  <%= @currency.cities %>
</p>

<%= link_to 'Edit', edit_currency_path(@currency) %> |
<%= link_to 'Destroy', @currency, method: :delete, data: { confirm: 'Are you sure?' } %> |
<%= link_to 'Back', currencies_path %>

app/views/layouts/_footer.html.erb
<footer class="footer">
  <small>
    © Foreign Savvy ™
  </small>
  <nav>
    <ul>
      <li><a href="mailto:ForeignSavvy@gmail.com?Subject=Contact%20Us" target="_top">Contact</a></li>
      <li><%= link_to "Privacy", privacy_path %></li>
      <li><%= link_to "Terms", terms_path %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
<script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= full_title(yield(:title)) %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <%= render 'layouts/shim' %>
  <link href='http://fonts.googleapis.com/css?family=Raleway:200,400,600' rel='stylesheet' type='text/css'>
</head>
<body>
	<%= render 'layouts/header' unless @header2 %>
  <%= render 'layouts/header2' if @header2 %>
  <div class="container">
    <%= yield %>
    <%= render 'layouts/footer' unless @skip_footer %>
  </div>
</body>
</html>

app/views/static_pages/about.html.erb
<% provide(:title, 'About') %>
<h1>Jetsi</h1>
<p>
  This is the about page for the
  <a href="#">Jetsi</a>
  application.
</p>

app/views/static_pages/contact.html.erb
<% provide(:title, 'Contact') %>
<h1>Jetsi</h1>
<p>
  This is the contact page for the
  <a href="#">Jetsi</a>
  application.
</p>

app/views/static_pages/help.html.erb
<% provide(:title, 'Help') %>
<h1>Jetsi</h1>
<p>
  This is the help page for the
  <a href="#">Jetsi</a>
  application.
</p>

app/views/static_pages/home.html.erb
<div id="boxgallery" class="boxgallery" data-effect="effect-1">
	<div class="bgpanel"><%= image_tag("image8_compressed.jpg", alt: "Beach") %></div>
	<div class="bgpanel"><%= image_tag("image9_compressed.jpg", alt: "Beach") %></div>
	<div class="bgpanel"><%= image_tag("image10_compressed.jpg", alt: "Beach") %></div>
	<div class="bgpanel"><%= image_tag("image11_compressed.jpg", alt: "Beach") %></div>
</div>

<div class="homebox">
	<h1>Foreign Savvy <span>travel more, spend less</span></h1>
	<div>
		<%= link_to "Tourism", tourism_path %>
		<%= link_to "Business", business_path %>
		<%= link_to "How it Works", timeline_path %>
	</div>
</div>

<script>
	new BoxesFx( document.getElementById( 'boxgallery' ) );
</script>